### ISSUE TITLE
not hiding attributes/item flags

### ISSUE THREAD

**Issue by Melon-Oof** [Maxlego08/zShop#6]
![Screenshot 2024-04-14 145748](https://github.com/Maxlego08/zShop/assets/147187344/8ea142f6-7478-4ee9-8c85-89276f5a5155)

This below is the item/block in the shop gui
```
  spawners:
    item:
      material: SPAWNER
      name: "#bb2008sᴘᴀᴡɴᴇʀs"
      lore:
        - ""
        - "&f➥ &7Click to access the #bb2008spawners"
    type: INVENTORY
    inventory: "spawners"
    plugin: "zShop"
    slot: 14
    flags:
      - HIDE_ATTRIBUTES
      - HIDE_PLACED_ON
      - HIDE_POTION_EFFECTS
      - HIDE_ARMOR_TRIM
      - HIDE_DYE
      - HIDE_ENCHANTS
      - HIDE_UNBREAKABLE
```

following this thread https://www.spigotmc.org/threads/remove-spawner-lore-1-20-1.609857/ this shouldve been hidden/not displayed, zShop ver is 3.0.9, server version is Paper 1.20.4 build 461, zMenu ver is 1.0.3.0
