### ISSUE TITLE
Add actions for clicks

### ISSUE THREAD

**Issue by NoltoxGit** [Maxlego08/zShop#8]
Hello,
Would it be possible to add the possibility of modifying the action performed by clicks in the config?

This could be useful for servers who only buy or sell items in their shops.

## Exemple of the config for this :
```yml
  # Sets actions for specified clicks in shop.
  # Allowed click types: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/inventory/ClickType.html
  # Allowed values: BUY_SELECTION_ITEM, SELL_SELECTION_ITEM, SELL_ALL_ITEM, BUY_SINGLE_ITEM, SELL_SINGLE_ITEM
  Click_Types:
    RIGHT: SELL_SELECTION_ITEM
    SHIFT_RIGHT: SELL_SINGLE_ITEM
    SWAP_OFFHAND: SELL_ALL_ITEM
    LEFT: BUY_SELECTION_ITEM
    SHIFT_LEFT: BUY_SINGLE_ITEM
```
